#!/usr/bin/python3

def square_matrix_simple(matrix=[]):
    """
        This function computes the square of all
        integers of a matrix
    Args:
        matrix: The matrix of integer
    Returns:
        A matrix
    """
    tmp = []
    newmatrix = []
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            tmp.append(matrix[i][j] * matrix[i][j])
        newmatrix.append(tmp.copy())
        tmp.clear()
   
   #newmatrix = list(map(lambda x: [i * i for i in x], matrix))
    return newmatrix
